Repository Data-Science-Community-SRM/Algorithms-for-Programming, pull requests merged in 2020-10, with the labels that each got.

#8 add merge sort algorithm
  Merge sort/Basic Questions/01. merge-two-sorted-arrays.cpp
  Merge sort/Basic Questions/02. merge-sort-algorithm.cpp
  Merge sort/Basic Questions/basicquestions.md
Labels: PR: reviewed changes requested, hacktoberfest accepted

#10 Added BFS according to the format mentioned.
  Breadth-first search/Basic Questions/01. Breadth-first-search.cpp
  Breadth-first search/Basic Questions/basicquestions.md
  Insertion sort/Basic Questions/01. Insertion-sort.cpp
  Insertion sort/Basic Questions/basicquestions.md
Labels: PR: reviewed changes requested, hacktoberfest accepted

#11 Adding Notes to Binary Search
  Binary Search/Notes/notes.md
Labels: PR: reviewed changes requested, hacktoberfest accepted

#12 Adding notes to Insertion sort
  Insertion sort/Notes/notes.md
Labels: PR: reviewed changes requested, hacktoberfest accepted

#16 Added Selection Sort according to the format mentioned
  Selection sort/Basic Questions/01. Selection-sort.cpp
  Selection sort/Basic Questions/basicquestions.md
Labels: hacktoberfest accepted

#15 Add Basic Quick Sort
  Quick sort/Basic Questions/Sorting an array using Quick Sort.cpp
Labels: PR: reviewed changes requested, hacktoberfest accepted

#9 Binary search Basic Question
  Binary Search/Basic Questions/basicquestions.md
Labels: hacktoberfest-accepted

#18 Selection sort Notes added
  Insertion sort/Notes/Insertion sort notes.pdf
  Selection sort/Notes/Selection Sort Notes.pdf
Labels: PR: reviewed changes requested, hacktoberfest-accepted

#20 Updated HIT button
  README.md
Labels: PR: reviewed changes requested, hacktoberfest-accepted

#22 Shashank
  Binary Search/Notes/Binary Search Notes.pdf
  Merge sort/Notes/Merge sort algorithm notes.pdf
  Towers of Hanoi/Notes/Tower of Hanoi Notes.pdf
Labels: PR: reviewed changes requested, hacktoberfest-accepted

#23 Patch1
  Merge sort/Basic Questions/03. merge-two-sorted-arrays.py
  Merge sort/Basic Questions/basicquestions.md
  Towers of Hanoi/Basic Questions/01. towerofhanoi.py
  Towers of Hanoi/Basic Questions/basicquestions.md
Labels: PR: reviewed changes requested, hacktoberfest-accepted
